/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba_genetika;

import java.util.Arrays;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.SwingConstants;


/**
 *
 * @author Jaka Pratama
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
     public  String[] insiasi_kromosom = {"1","2","3"};
     int i;
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        Proses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tampil_c1 = new javax.swing.JLabel();
        tampil_c6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        tampil_c2 = new javax.swing.JLabel();
        tampil_c3 = new javax.swing.JLabel();
        tampil_c4 = new javax.swing.JLabel();
        tampil_c5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tampil_q_1 = new javax.swing.JLabel();
        tampil_q_2 = new javax.swing.JLabel();
        tampil_q_3 = new javax.swing.JLabel();
        tampil_q_4 = new javax.swing.JLabel();
        tampil_q_5 = new javax.swing.JLabel();
        tampil_q_6 = new javax.swing.JLabel();
        tot_fitness = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        view_p1 = new javax.swing.JLabel();
        view_p2 = new javax.swing.JLabel();
        view_p3 = new javax.swing.JLabel();
        view_p4 = new javax.swing.JLabel();
        view_p5 = new javax.swing.JLabel();
        view_p6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        view_c1 = new javax.swing.JLabel();
        view_c2 = new javax.swing.JLabel();
        view_c3 = new javax.swing.JLabel();
        view_c4 = new javax.swing.JLabel();
        view_c5 = new javax.swing.JLabel();
        view_c6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pembentukan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        view_eval_f1 = new javax.swing.JLabel();
        view_eval_f3 = new javax.swing.JLabel();
        view_eval_f4 = new javax.swing.JLabel();
        view_eval_f5 = new javax.swing.JLabel();
        view_eval_f6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        view_eval_f2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        view_r1 = new javax.swing.JLabel();
        view_r2 = new javax.swing.JLabel();
        view_r3 = new javax.swing.JLabel();
        view_r4 = new javax.swing.JLabel();
        view_r5 = new javax.swing.JLabel();
        view_r6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        view_cr1 = new javax.swing.JLabel();
        view_cr2 = new javax.swing.JLabel();
        view_cr3 = new javax.swing.JLabel();
        view_cr4 = new javax.swing.JLabel();
        view_cr5 = new javax.swing.JLabel();
        view_cr6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        view_pc = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        view_rk1 = new javax.swing.JLabel();
        view_rk2 = new javax.swing.JLabel();
        view_rk3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TSP with Genetika");
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });

        jLabel1.setText("PROGRAM ALGORITMA GENETIKA");

        jLabel4.setText("PROSES INISIASI");

        tampil_c1.setText("C[1] = ");

        tampil_c6.setText("C[6] = ");

        tampil_c2.setText("C[2] = ");

        tampil_c3.setText("C[3] = ");

        tampil_c4.setText("C[4] = ");

        tampil_c5.setText("C[5] = ");
        tampil_c5.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tampil_c2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tampil_c3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tampil_c4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tampil_c5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(tampil_c2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(tampil_c3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampil_c4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampil_c5)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(60, 60, 60))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tampil_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampil_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tampil_c1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tampil_c6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("SELEKSI");

        tampil_q_1.setText("Q[1] =");

        tampil_q_2.setText("Q[2] =");

        tampil_q_3.setText("Q[3] =");

        tampil_q_4.setText("Q[4] =");

        tampil_q_5.setText("Q[5] =");

        tampil_q_6.setText("Q[6] =");

        tot_fitness.setText("TOTAL FITNESS = ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(tot_fitness)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tampil_q_1)
                    .addComponent(tampil_q_2)
                    .addComponent(tampil_q_3)
                    .addComponent(tampil_q_4)
                    .addComponent(tampil_q_5)
                    .addComponent(tampil_q_6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampil_q_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampil_q_2)
                .addGap(16, 16, 16)
                .addComponent(tampil_q_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampil_q_4)
                .addGap(13, 13, 13)
                .addComponent(tampil_q_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampil_q_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tot_fitness)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel6.setText("PROSES ROULETE WHEEL");

        view_p1.setText("P[1] =");

        view_p2.setText("P[2] =");

        view_p3.setText("P[3] =");

        view_p4.setText("P[4] =");

        view_p5.setText("P[5] =");

        view_p6.setText("P[6] =");

        jLabel7.setText("KUMULATIF");

        view_c1.setText("C[1] = ");

        view_c2.setText("C[2] = ");

        view_c3.setText("C[3] = ");

        view_c4.setText("C[4] = ");

        view_c5.setText("C[5] = ");

        view_c6.setText("C[6] = ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel7))
                    .addComponent(view_c1)
                    .addComponent(view_c2)
                    .addComponent(view_c3)
                    .addComponent(view_c4)
                    .addComponent(view_c5)
                    .addComponent(view_c6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_c1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_c2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_c3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_c4)
                .addGap(13, 13, 13)
                .addComponent(view_c5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_c6)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_p1)
                    .addComponent(view_p2)
                    .addComponent(view_p3)
                    .addComponent(view_p4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6))
                            .addComponent(view_p5)
                            .addComponent(view_p6))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(view_p1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_p4)
                .addGap(13, 13, 13)
                .addComponent(view_p5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_p6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("PEMBENTUKAN KROMOSOM");

        pembentukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembentukanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pembentukan, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(pembentukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jLabel5.setText("EVALUASI KROMOSOM");

        view_eval_f1.setText("F[1] = ");
        view_eval_f1.setToolTipText("");

        view_eval_f3.setText("F[3] =");

        view_eval_f4.setText("F[4] =");

        view_eval_f5.setText("F[5] =");

        view_eval_f6.setText("F[6] =");
        view_eval_f6.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        view_eval_f2.setText("F[2] =");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(view_eval_f1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(view_eval_f6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_eval_f5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_eval_f4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_eval_f3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(view_eval_f2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(302, 302, 302))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addComponent(view_eval_f1)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(view_eval_f2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(view_eval_f3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_eval_f4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_eval_f5)
                .addGap(11, 11, 11)
                .addComponent(view_eval_f6)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel9.setText("NILAI R");

        view_r1.setText("R[1] = ");

        view_r2.setText("R[2] = ");

        view_r3.setText("R[3] = ");

        view_r4.setText("R[4] = ");

        view_r5.setText("R[5] = ");

        view_r6.setText("R[6] = ");

        jLabel10.setText("CROSSOVER");

        view_cr1.setText("R[1] = ");

        view_cr2.setText("R[2] = ");

        view_cr3.setText("R[3] = ");

        view_cr4.setText("R[4] = ");

        view_cr5.setText("R[5] = ");

        view_cr6.setText("R[6] = ");

        jLabel11.setText("NILAI ACAK");

        view_pc.setText("PC = ");

        jLabel12.setText("R[K] < PC");

        view_rk1.setText("jLabel13");

        view_rk2.setText("jLabel13");

        view_rk3.setText("jLabel13");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_cr3)
                    .addComponent(view_cr4)
                    .addComponent(view_cr5)
                    .addComponent(view_cr6)
                    .addComponent(view_cr2)
                    .addComponent(view_cr1)
                    .addComponent(view_pc)
                    .addComponent(jLabel12)
                    .addComponent(view_rk1)
                    .addComponent(view_rk2)
                    .addComponent(view_rk3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_pc)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addComponent(view_cr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_cr2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_cr3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_cr4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_cr5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_cr6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_rk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_rk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_rk3)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_r1)
                    .addComponent(view_r2)
                    .addComponent(view_r3)
                    .addComponent(view_r4)
                    .addComponent(view_r5)
                    .addComponent(view_r6)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_r1)
                .addGap(4, 4, 4)
                .addComponent(view_r2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_r3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_r4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_r5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_r6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Proses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Proses)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed

        // TODO add your handling code here:
    
    //PROSES PEMBENTUKAN KROMOSOM//
    
    String ket = "Berhasil";
    pembentukan.setText(ket);

    String[] nilai = {"A","B","C","D","E","F"};
    
  //String ubah ="";  
  while (i <=6){
    
        i++;
        pembentukan.setText(Arrays.toString(nilai) + "\n");
        
        
    }
  
  
  
  
  //PROSES INISIASI
  String[] c_1 = {"A","B","C","D","E","F"};
  String[] c_2 = {"A","C","D","E","F","B"};
  String[] c_3 = {"A","D","E","F","B","C"};
  String[] c_4 = {"A","E","F","B","C","D"};
  String[] c_5 = {"A","F","B","C","D","E"};
  String[] c_6 = {"A","F","C","B","D","E"};
  //---------------------------------------
  
   tampil_c1.setText("C[1] = "+Arrays.toString(c_1));
   tampil_c2.setText("C[2] = "+Arrays.toString(c_2));
   tampil_c3.setText("C[3] = "+Arrays.toString(c_3));
   tampil_c4.setText("C[4] = "+Arrays.toString(c_4));
   tampil_c5.setText("C[5] = "+Arrays.toString(c_5));
   tampil_c6.setText("C[6] = "+Arrays.toString(c_6));
   
// EVALUASI KROMOSOM
int AB=5;
int BC=4;
int CD=9;
int DE=8;
int EF=5;
int FA=3;
int FB=7;
int AC=7;
int BA;
int CA;
int AE=6;
int AD= 8;
BA=AB;
CA=AC;

int AF,EA;
AF=FA;
EA=AE;
int DA;
DA=AD;
int BD =6;
int CB =4;
int FC =7;
        
String tampil_eval_f1 = "F[1] = AB+BC +CD + DE +EF+FA";
String tampil_eval_f2 = "F[2] = AC+CD+DE+EF+FB+BA";
String tampil_eval_f3 = "F[3] = AD+DE+EF+FB+BC+CA";
String tampil_eval_f4 = "F[4] = AE+EF+FB+BC+CD+DA";
String tampil_eval_f5 = "F[5] = AF+FB+BC+CD+DE+EA";
String tampil_eval_f6 = "F[6] = AF+FC+CB+BD+DE+EA";


view_eval_f1.setText(tampil_eval_f1);
view_eval_f2.setText(tampil_eval_f2);
view_eval_f3.setText(tampil_eval_f3);
view_eval_f4.setText(tampil_eval_f4);
view_eval_f5.setText(tampil_eval_f5);
view_eval_f6.setText(tampil_eval_f6);


float f_1 = AB+BC +CD + DE +EF+FA;
float f_2 = AC+CD+DE+EF+FB+BA;
float f_3 = AD+DE+EF+FB+BC+CA;
float f_4 = AE+EF+FB+BC+CD+DA;
float f_5 = AF+FB+BC+CD+DE+EA;
float f_6 = AF+FC+CB+BD+DE+EA;


//SELEKSI

float q_1 = (1/f_1);

float q_2 = (1/f_2);
float q_3 = 1/f_3;
float q_4 = 1/f_4;
float q_5 = 1/f_5;
float q_6 = 1/f_6;
float total = q_1+q_2+q_3+q_4+q_5+q_6;


tampil_q_1.setText("Q[1] = "+q_1);
tampil_q_2.setText("Q[2] = "+q_2);
tampil_q_3.setText("Q[3] = "+q_3);
tampil_q_4.setText("Q[4] = "+q_4);
tampil_q_5.setText("Q[5] = "+q_5);
tampil_q_6.setText("Q[6] = "+q_6);


float total_fitness =total;

tot_fitness.setText("Total Fitness = "+String.valueOf(total_fitness));

//P1
float p1 = q_1/total;
float p2 = q_2/total;
float p3 = q_3/total;
float p4 = q_4/total;
float p5 = q_5/total;
float p6 = q_6/total;

view_p1.setText("P[1] = "+p1);
view_p2.setText("P[2] = "+p2);
view_p3.setText("P[3] = "+p3);
view_p4.setText("P[4] = "+p4);
view_p5.setText("P[5] = "+p5);
view_p6.setText("P[6] = "+p6);

//kumulatif c[1]

float c1 = p1;
float c2 = p1 + p2;
float c3 = c2 + p3;
float c4 = c3 + p4;
float c5 = c4 + p5;
float c6 = c5 + p6;

view_c1.setText("C[1] = "+c1);
view_c2.setText("C[2] = "+c2);
view_c3.setText("C[3] = "+c3);
view_c4.setText("C[4] = "+c4);
view_c5.setText("C[5] = "+c5);
view_c6.setText("C[6] = "+c6);

//nilai R
ArrayList<Float> arrayList = new ArrayList<>();
arrayList.add((float)0.121);
arrayList.add((float)0.212);
arrayList.add((float)0.008);
arrayList.add((float)0.702);
arrayList.add((float)0.888);
arrayList.add((float)0.923);

view_r1.setText("R[1] = "+String.valueOf(arrayList.get(0)));
view_r2.setText("R[2] = "+String.valueOf(arrayList.get(1)));
view_r3.setText("R[3] = "+String.valueOf(arrayList.get(2)));
view_r4.setText("R[4] = "+String.valueOf(arrayList.get(3)));
view_r5.setText("R[5] = "+String.valueOf(arrayList.get(4)));
view_r6.setText("R[6] = "+String.valueOf(arrayList.get(5)));

//      CROSSOVER
//Probabilitas Crossover
float pc =(float) 0.25;
view_pc.setText("PC = "+pc);

//nilai R
arrayList.add((float)0.101);
arrayList.add((float)0.213);
arrayList.add((float)0.100);
arrayList.add((float)0.633);
arrayList.add((float)0.785);
arrayList.add((float)0.901);

view_cr1.setText("R[1] = "+String.valueOf(arrayList.get(0)));
view_cr2.setText("R[2] = "+String.valueOf(arrayList.get(1)));
view_cr3.setText("R[3] = "+String.valueOf(arrayList.get(2)));
view_cr4.setText("R[4] = "+String.valueOf(arrayList.get(3)));
view_cr5.setText("R[5] = "+String.valueOf(arrayList.get(4)));
view_cr6.setText("R[6] = "+String.valueOf(arrayList.get(5)));
         

if (pc < arrayList.get(0)){
       view_rk1.setText("C[1]");
}
if (pc < arrayList.get(1)){
       view_rk2.setText("C[2]");
}
if (pc < arrayList.get(2)){
       view_rk3.setText("C[3]");
}


    
    }//GEN-LAST:event_ProsesActionPerformed

    private void pembentukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembentukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembentukanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Proses;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pembentukan;
    private javax.swing.JLabel tampil_c1;
    private javax.swing.JLabel tampil_c2;
    private javax.swing.JLabel tampil_c3;
    private javax.swing.JLabel tampil_c4;
    private javax.swing.JLabel tampil_c5;
    private javax.swing.JLabel tampil_c6;
    private javax.swing.JLabel tampil_q_1;
    private javax.swing.JLabel tampil_q_2;
    private javax.swing.JLabel tampil_q_3;
    private javax.swing.JLabel tampil_q_4;
    private javax.swing.JLabel tampil_q_5;
    private javax.swing.JLabel tampil_q_6;
    private javax.swing.JLabel tot_fitness;
    private javax.swing.JLabel view_c1;
    private javax.swing.JLabel view_c2;
    private javax.swing.JLabel view_c3;
    private javax.swing.JLabel view_c4;
    private javax.swing.JLabel view_c5;
    private javax.swing.JLabel view_c6;
    private javax.swing.JLabel view_cr1;
    private javax.swing.JLabel view_cr2;
    private javax.swing.JLabel view_cr3;
    private javax.swing.JLabel view_cr4;
    private javax.swing.JLabel view_cr5;
    private javax.swing.JLabel view_cr6;
    private javax.swing.JLabel view_eval_f1;
    private javax.swing.JLabel view_eval_f2;
    private javax.swing.JLabel view_eval_f3;
    private javax.swing.JLabel view_eval_f4;
    private javax.swing.JLabel view_eval_f5;
    private javax.swing.JLabel view_eval_f6;
    private javax.swing.JLabel view_p1;
    private javax.swing.JLabel view_p2;
    private javax.swing.JLabel view_p3;
    private javax.swing.JLabel view_p4;
    private javax.swing.JLabel view_p5;
    private javax.swing.JLabel view_p6;
    private javax.swing.JLabel view_pc;
    private javax.swing.JLabel view_r1;
    private javax.swing.JLabel view_r2;
    private javax.swing.JLabel view_r3;
    private javax.swing.JLabel view_r4;
    private javax.swing.JLabel view_r5;
    private javax.swing.JLabel view_r6;
    private javax.swing.JLabel view_rk1;
    private javax.swing.JLabel view_rk2;
    private javax.swing.JLabel view_rk3;
    // End of variables declaration//GEN-END:variables
}
